### ISSUE TITLE
Request: Rainy lure icon

### ISSUE THREAD

**Issue by ColdShadow80** [nileplumb/PkmnHomeIcons#4]
Request for rainy lure icon for PkmnHomeIcons/RDM_OS_128/pokestop

(And thanks, keep up the good work)

**Comment by nileplumb** [comment]
yup I ran out of time before work I was remaking the lures for this repo the other day, haven't forgotten :)

**Comment by nileplumb** [comment]
fixed in commit https://github.com/nileplumb/PkmnHomeIcons/commit/84a108de1a6cf5ee4caedb61150b41dc58d8c4e9

**Comment by ColdShadow80** [comment]
Thank you.
Just missing lured pokestop icon in folder: PkmnHomeIcons/RDM_OS_128/pokestop

**Comment by nileplumb** [comment]
> 
> 
> Thank you.
> Just missing lured pokestop icon in folder: PkmnHomeIcons/RDM_OS_128/pokestop

ah yeah ha I have access to some
