### ISSUE TITLE
Charmander ICON

### ISSUE THREAD

**Issue by nakratz** [nileplumb/PkmnHomeIcons#6]
Been using the old PMSF OS 128 folders before UICONs is being decided on. Found that Charmander 4.png in a couple of the Directories are actually using the Charmander with Cubone hat. Provided the links below of the 2 files I found that are possibly incorrect. 

https://github.com/nileplumb/PkmnHomeIcons/blob/master/UICONS_OS_128/pokemon/4.png
https://github.com/nileplumb/PkmnHomeIcons/blob/master/pmsf_OS_128/pokemon_icon_004_00.png

Thanks,

**Comment by nileplumb** [comment]
ha no one has ever brought  that up, wheel just script transferred the pack so makes sense I have a few edits locally to the uicons I'll change that one too

**Comment by nileplumb** [comment]
oh that'll be because it's always 4_172 now I guess

**Comment by nakratz** [comment]
I noticed it a while ago, and thought it was just a me issue because it showed him with Cubone hat on the menu and the Nest Flags on the map. But wild spawned Charmanders were the proper form. Never really looked further in to it until last night when I was updating stuff. :)
