### ISSUE TITLE
Tandemaus is missing

### ISSUE THREAD

**Issue by Cat333Pokemon** [nileplumb/PkmnHomeIcons#8]
Icons `924` and `924_s` are absent from all three sets (512×512, 512×512 no outline, and 128×128).

**Comment by nileplumb** [comment]
Yup thank you I noticed this earlier I just haven't pushed the update yet from home thanks for reminding meSent from my iPhoneOn 9 Jun 2023, at 16:47, Cat333Pokemon ***@***.***> wrote:﻿
Icons 924 and 924_s are absent from all three sets (512×512, 512×512 no outline, and 128×128).
